// Turkish translation mapping and capitals for major ISO_A2 codes
const countryData = {
    "TR": { name: "Türkiye", capital: "Ankara" },
    "US": { name: "Amerika Birleşik Devletleri", capital: "Washington, D.C." },
    "DE": { name: "Almanya", capital: "Berlin" },
    "FR": { name: "Fransa", capital: "Paris" },
    "GB": { name: "İngiltere", capital: "Londra" },
    "IT": { name: "İtalya", capital: "Roma" },
    "ES": { name: "İspanya", capital: "Madrid" },
    "RU": { name: "Rusya", capital: "Moskova" },
    "CN": { name: "Çin", capital: "Pekin" },
    "JP": { name: "Japonya", capital: "Tokyo" },
    "BR": { name: "Brezilya", capital: "Brasília" },
    "IN": { name: "Hindistan", capital: "Yeni Delhi" },
    "CA": { name: "Kanada", capital: "Ottawa" },
    "AU": { name: "Avustralya", capital: "Canberra" },
    "ZA": { name: "Güney Afrika", capital: "Pretoria" },
    "AR": { name: "Arjantin", capital: "Buenos Aires" },
    "MX": { name: "Meksika", capital: "Meksiko" },
    "EG": { name: "Mısır", capital: "Kahire" },
    "GR": { name: "Yunanistan", capital: "Atina" },
    "SE": { name: "İsveç", capital: "Stokholm" },
    "NO": { name: "Norveç", capital: "Oslo" },
    "FI": { name: "Finlandiya", capital: "Helsinki" },
    "KR": { name: "Güney Kore", capital: "Seul" },
    "SA": { name: "Suudi Arabistan", capital: "Riyad" },
    "IR": { name: "İran", capital: "Tahran" },
    "IQ": { name: "Irak", capital: "Bağdat" },
    "SY": { name: "Suriye", capital: "Şam" },
    "NL": { name: "Hollanda", capital: "Amsterdam" },
    "CH": { name: "İsviçre", capital: "Bern" },
    "BE": { name: "Belçika", capital: "Brüksel" },
    "PT": { name: "Portekiz", capital: "Lizbon" },
    "PL": { name: "Polonya", capital: "Varşova" },
    "UA": { name: "Ukrayna", capital: "Kiev" },
    "KZ": { name: "Kazakistan", capital: "Astana" },
    "AZ": { name: "Azerbaycan", capital: "Bakü" },
    "ID": { name: "Endonezya", capital: "Cakarta" },
    "PK": { name: "Pakistan", capital: "İslamabad" },
    "NG": { name: "Nijerya", capital: "Abuja" },
    "KE": { name: "Kenya", capital: "Nairobi" },
    "DZ": { name: "Cezayir", capital: "Cezayir" },
    "MA": { name: "Fas", capital: "Rabat" }
};
